<a href="https://colab.research.google.com/github/hongseoi/data_analysis/blob/main/AI_Based_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#3.2 데이터형
#bytes
x = b'bong'
type(x)

bytes

In [3]:
#list
x = ['a',2.3,3,b'bong']
print(type(x))

for i in range(len(x)):
  print(type(x[i]))

<class 'list'>
<class 'str'>
<class 'float'>
<class 'int'>
<class 'bytes'>


In [4]:
#tuple
x = (1,2,3)
type(x)

tuple

In [5]:
#dict
x = {'key1':100, 'key2':200}
type(x)

dict

In [6]:
#dict
x = dict(key1=100, key2=200)
type(x)

dict

In [7]:
#set
x = {"key1",'key2'}
type(x)

set

In [8]:
# set의 특성: 중복 불허용
x = {1,2,3,3}
x

{1, 2, 3}

In [10]:
#3.4 값의 할당
# 같은 값 할당
x = y = 0
[x,y]

[0, 0]

In [14]:
#각각의 값 할당
x, y = 0,0.9
[x,y]

[0, 0.9]

In [15]:
#값 바꾸기
x ,y = y,x
[x,y]

[0.9, 0]

In [16]:
#정의는 되었으나 값 없음
x = None
[x, type(x)]

[None, NoneType]

In [17]:
#변수제거
del x
x

NameError: ignored

In [19]:
# 3.5형변환
#문자열에서 정수로
[int('100'), ord('\n')] #ord():문자의 유니코드값 반환

[100, 10]

In [20]:
#16진법으로 표시된 문자열을 정수로
int('ff', base=16)

255

In [21]:
#실수를 정수로
[int(2.1),round(13.2)]

[2, 13]

In [22]:
#정수를 문자로
chr(97)

'a'

In [23]:
#리스트를 바이트로
bytes([97,98,99,100])

b'abcd'

In [24]:
#문자열을 리스트로
list('abxd')

['a', 'b', 'x', 'd']

In [25]:
#리스트를 딕셔너리로
dict([(1,"abc"),(2,"cde")])

{1: 'abc', 2: 'cde'}

In [26]:
#문자열을 집합으로
set('abcd')

{'a', 'b', 'c', 'd'}

In [30]:
#리스트를 문자열로
x = "-".join(['bong','ju','kang'])
x

'bong-ju-kang'

In [32]:
#문자열을 리스트로
d = x.split('-')
d

['bong', 'ju', 'kang']

In [33]:
#nonetype을 bool로
bool(None)

False

In [34]:
#0논리값
bool(0)

False

In [35]:
bool(1)

True

In [36]:
#bool(False)

In [38]:
#널 문자열 논리값
bool("")

False

In [39]:
#3.6 인덱싱: 원소 제거
x = [2,3,4,5,6]
del x[:2]
x

[4, 5, 6]

In [40]:
#3.9 모듈 가져오기
import sys
sys.path # 이 안에 있어야 사용 가능

['/content',
 '/env/python',
 '/usr/lib/python37.zip',
 '/usr/lib/python3.7',
 '/usr/lib/python3.7/lib-dynload',
 '',
 '/usr/local/lib/python3.7/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/local/lib/python3.7/dist-packages/IPython/extensions',
 '/root/.ipython']

In [41]:
#numpy 가져오기
import numpy as np
np.__version__

'1.21.6'

In [42]:
#3.11 수학 연산
import numpy as np

#행렬곱: @
x = np.array([[1,2],[3,4]])
y = np.array([[0,1],[1,0]])
x@y


array([[2, 1],
       [4, 3]])

In [43]:
#원소별 곱
x*y

array([[0, 2],
       [3, 0]])

In [44]:
#sin 함수
np.sin(np.pi/2)

1.0

In [45]:
#자연로그
np.log([1,np.e, np.e**2, 0])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([  0.,   1.,   2., -inf])

In [46]:
#천장함수
np.ceil(9.9)

10.0

In [47]:
#3.12 조건 반복문
name = 'bong ju kang'
for index, value in enumerate(name): #enumerate(): 인덱스와 원소로 이루어진 투플 반환
  if value =='g':
    print('index num:',index)

index num: 3
index num: 11


In [48]:
[name[index] for index in range(len(name))]

['b', 'o', 'n', 'g', ' ', 'j', 'u', ' ', 'k', 'a', 'n', 'g']

In [51]:
# 3.13 generic operation
#일반연산: len min max sorted

name = 'bong ju kang'
value = "123456789"

[len(name), len(value), min(value), max(name), sorted(name)]

[12, 9, '1', 'u', [' ', ' ', 'a', 'b', 'g', 'g', 'j', 'k', 'n', 'n', 'o', 'u']]

In [52]:
#일반연산: enumerate
[{a:b} for a, b in enumerate(name)]

[{0: 'b'},
 {1: 'o'},
 {2: 'n'},
 {3: 'g'},
 {4: ' '},
 {5: 'j'},
 {6: 'u'},
 {7: ' '},
 {8: 'k'},
 {9: 'a'},
 {10: 'n'},
 {11: 'g'}]

In [54]:
#일반연산:zip(): 같은 위치에 있는 값을 반환
[val for val in zip(('a','b','c'),('c','d','e','f'))]

[('a', 'c'), ('b', 'd'), ('c', 'e')]

In [56]:
[val for val in zip(name, value)]

[('b', '1'),
 ('o', '2'),
 ('n', '3'),
 ('g', '4'),
 (' ', '5'),
 ('j', '6'),
 ('u', '7'),
 (' ', '8'),
 ('k', '9')]

In [57]:
#일반연산자: index(위치), count(건수)
[name.index('k'), name.count('g')]

[8, 2]

In [58]:
# 일반연산자 in
x = 'b'
x in name

True

In [62]:
#3.14 리스트 연산: append remove extend insert pop sort reverse
# 리스트 생성
value = []
value

[]

In [63]:
#원소 추가
value.append('b')
value.append('a')
value.append('n')
value.append('e')
value.append('n')
value.append('e')
value

['b', 'a', 'n', 'e', 'n', 'e']

In [64]:
#원소 제거
value.remove('b')
value

['a', 'n', 'e', 'n', 'e']

In [65]:
# 순서열 추가:extend
value.extend('bnn')
value

['a', 'n', 'e', 'n', 'e', 'b', 'n', 'n']

In [66]:
#원소 마지막 값 제거
value.pop()
value

['a', 'n', 'e', 'n', 'e', 'b', 'n']

In [67]:
#원소 위치값 제거 
value.pop(-1)
value

['a', 'n', 'e', 'n', 'e', 'b']

In [68]:
#정렬: sort, reverse
value.sort()
value

['a', 'b', 'e', 'e', 'n', 'n']

In [69]:
#3.15 딕셔너리 연산: get update del pop popitem
#딕셔너리 생성
score = {'lang':80, 'math':90, 'his':75}
score


{'lang': 80, 'math': 90, 'his': 75}

In [70]:
#키 조회
score.keys()

dict_keys(['lang', 'math', 'his'])

In [71]:
#딕셔너리 값 조회: 키 순서대로
score.values()

dict_values([80, 90, 75])

In [72]:
#딕셔너리 값 조회: 키와 get
[score['lang'], score.get('lang')]

[80, 80]

In [75]:
#딕셔너리 값 수정: 키와 update
score['math'] = 100
score.update({'math':100})
score

{'lang': 80, 'math': 100, 'his': 75}

In [76]:
#특정 키 제거: del
del score['lang']
score

{'math': 100, 'his': 75}

In [78]:
#딕셔너리 초기화
score.clear()
score

{}

In [79]:
#3.16 집합 set 연산
# 집합 정의
A = {'a','b','c'}
B = {'b','c','d','e'}
[A,B]

[{'a', 'b', 'c'}, {'b', 'c', 'd', 'e'}]

In [80]:
#합집합
A|B


{'a', 'b', 'c', 'd', 'e'}

In [81]:
# 교집합
A&B

{'b', 'c'}

In [82]:
#차집합 
A-B

{'a'}

In [83]:
# 집합 비교
C = A|B
[A<C, A<B, B<C, A==B]

[True, False, True, False]

In [84]:
#원소 추가
A.add('a')

In [85]:
#집합 추가
A.update({1,2,3})
A

{1, 2, 3, 'a', 'b', 'c'}

In [86]:
#원소 제거
A.remove('a')

In [87]:
#집합 복사
D = A.copy()
D

{1, 2, 3, 'b', 'c'}

In [88]:
#3.18 문자열 연산: strip, count, index, is, upper, lower, split, join
#문자열 생성
name ='\n bong ju kang'
name


'\n bong ju kang'

In [90]:
#문자열 앞뒤 스페이스 제거:strip
name.strip()

'bong ju kang'

In [91]:
#대소문자 변환
['KANG'.lower(), 'banana'.upper()]

['kang', 'BANANA']

In [92]:
#대소문자 서로 변환:swapcase
'Kang Bong Ju'.swapcase()

'kANG bONG jU'

In [93]:
#숫자, 문자로만 구성된 열인지 확인:isalnum()
'Bongjur Kang 2020!'.isalnum()

False

In [94]:
#문자열 분리
'ka,ng'.split(',')

['ka', 'ng']

In [95]:
#문자열 결합
','.join(['kang','bong'])

'kang,bong'

In [97]:
#3.19 포멧 구성하기
'''
아무 데이터 형이나 지정된 특별한 형식으로 문자열을 만들어주는것
포멧지시문.format(포맷할 값)
'''


'\n아무 데이터 형이나 지정된 특별한 형식으로 문자열을 만들어주는것\n포멧지시문.format(포맷할 값)\n'

In [99]:
#소수점 2째자리까지
"${:.2f}".format(234,12355)

'$234.00'

In [100]:
#콤마 포멧
"{:,}원".format(1934829347893)

'1,934,829,347,893원'

In [101]:
# 콤마 포멧 + 소수점 이하 1째자리
"{:,.1f}원".format(1239234)

'1,239,234.0원'