In [18]:
import numpy as np
import matplotlib.pyplot as plt
import random


In [4]:
#1
a1 = np.arange(1,21)
re_a1 = a1[::-1]

print(a1)
print(re_a1)
print("num_arr내의 모든 원소의 합:", np.sum(a1))
print(a1.reshape(5,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
num_arr내의 모든 원소의 합: 210
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [52]:
#2.1
n_arr = np.arange(25).reshape(5,5)
n_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [8]:
#2.2
print("첫 원소:",n_arr[0][0])
print("마지막 원소:", n_arr[-1][-1])

첫 원소: 0
마지막 원소: 24


In [11]:
#2.3
n_arr[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
#2.4
n_arr[2:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
#2.5
n_arr[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [16]:
#2.6
n_arr[::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [17]:
#2.7
n_arr[:2].reshape(5,2)


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [54]:
#3.1
np.random.seed(100)
a = np.random.rand(3,3,3)
a

array([[[0.54340494, 0.27836939, 0.42451759],
        [0.84477613, 0.00471886, 0.12156912],
        [0.67074908, 0.82585276, 0.13670659]],

       [[0.57509333, 0.89132195, 0.20920212],
        [0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101]],

       [[0.81622475, 0.27407375, 0.43170418],
        [0.94002982, 0.81764938, 0.33611195],
        [0.17541045, 0.37283205, 0.00568851]]])

In [55]:
#3.2
np.max(a)

0.9786237847073697

In [56]:
#3.3
print("a의 원소들 중 최댓값의 위치:", np.argmax(a))

a의 원소들 중 최댓값의 위치: 15


In [57]:
#4.1
n_array = np.ones((5,5))
n_array[::2,1::2] = 0
n_array[1::2,::2] = 0
n_array


array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

In [45]:
#4.2
print("행렬의 행 방향 성분의 합:", np.sum(n_array, axis=0))

행렬의 행 방향 성분의 합: [5. 2. 5. 2. 5.]


In [59]:
#sol
n_arr = (np.arange(1,26)%2).reshape(5,5)
n_arr

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [36]:
#5
a = np.arange(0,32).reshape(4,4,2)
print("10번째 원소:", a.flatten()[9])
print("20번째 원소: ", a.flatten()[19])

10번째 원소: 9
20번째 원소:  19


In [31]:
#6
x1 = [i for i in range(100)]
x2 = [i + np.random.randint(1,10) for i in range(100)]
x3 = [i+np.random.randint(1,50) for i in range(100)]
x4 = [np.random.randint(1,100) for i in range(100)]

print(np.corrcoef(x1, x2))
print(np.corrcoef(x1,x3))
print(np.corrcoef(x1,x4))

# x1과 가장 상관관계 높은 리스트: x2
# x1과 가장 상관관계 낮은 리스트: x3

[[1.         0.99623107]
 [0.99623107 1.        ]]
[[1.         0.88950727]
 [0.88950727 1.        ]]
[[1.         0.00141208]
 [0.00141208 1.        ]]


In [60]:
#6 solv
result = np.corrcoef([x1,x2,x3,x4])
print(result)


[[ 1.          0.99623107  0.88950727  0.00141208]
 [ 0.99623107  1.          0.88613659  0.00161037]
 [ 0.88950727  0.88613659  1.         -0.03587432]
 [ 0.00141208  0.00161037 -0.03587432  1.        ]]
